# Use NVIDIA HPC SDK image
FROM nvcr.io/nvidia/nvhpc:23.11

# Set the working directory
WORKDIR /workspace

# Copy your code into the container
COPY . /workspace

# Default command to compile your Fortran code
CMD ["make libs FCOMP=NVIDIA && make FCOMP=NVIDIA"]
