# Use NVIDIA HPC SDK image
FROM nvcr.io/nvidia/nvhpc:24.11-devel-cuda_multi-ubuntu22.04

# Install gfortran
RUN apt-get update && apt-get install -y gfortran libopenmpi-dev libfftw3-dev && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /workspace

# Copy your code into the container
COPY . /workspace

# Default command to compile your Fortran code
CMD ["/bin/bash", "-c","make libs FCOMP=NVIDIA && make FCOMP=NVIDIA"]
