name: test-GNU-opt

on:
  - pull_request
  - push

env:
  compiler: 'GNU'
  mode: 'opt'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Check out actions
        uses: actions/checkout@v4
      - name: Build CaNS
        uses: ./.github/actions/build
        with:
          compiler: $compiler
          mode: $mode
          name: $compiler-$mode
