name: run-default

on:
  - pull_request
  - push
  - workflow_dispatch

env:
  # This matrix is the jobs that are executed at every 'push'
  FAST_MATRIX : >-
    {
      "compiler": [
        { "name": "NVIDIA" }
      ],
      "mode": [
        { "name": "opt", "flags": "" }
      ]
    }
  # This matrix is the jobs that are executed only for pull requests or manually
  #FULL_MATRIX : >-
  #  {
  #    "compiler": [
  #      { "name": "GNU" },
  #      { "name": "NVIDIA", "version": "24.11", "year": 2024 },
  #      { "name": "INTEL", "intel_version": "2024.0.0.49564", "hpc_version": "2024.0.0.49589" }
  #    ],
  #    "mode": [
  #      { "name": "opt", "flags": "" },
  #      { "name": "dbg", "flags": " OPT_DEBUG_MAX=1 " }
  #    ]
  #  }
  FULL_MATRIX : >-
    {
      "compiler": [
        { "name": "INTEL", "intel_version": "2024.0.0.49564", "hpc_version": "2024.0.0.49589" }
      ],
      "mode": [
        { "name": "dbg", "flags": " FFLAGS_DEBUG_MAX=1 FFLAGS_OPT=0 " }
      ]
    }

jobs:
  parse-matrix:
    runs-on: ubuntu-latest
    outputs:
      compiler_matrix: ${{ steps.export-matrix.outputs.matrix }}
    steps:
      - name: Parse and prepare compiler strategy
        id: export-matrix
        shell: bash
        run: |
          # Extract JSON from the global COMPILER_MATRIX
          if [ "${GITHUB_EVENT_NAME}" == "push" ]; then
            STRATEGY=$(echo $FAST_MATRIX | jq -c '.')
          else
            STRATEGY=$(echo $FULL_MATRIX | jq -c '.')
          fi
          # Export the entire JSON as a single string for reuse
          echo "matrix=$STRATEGY" >> "$GITHUB_OUTPUT"          
          # Parse and print compilers and modes in Bash
          COMPILERS=$(echo $STRATEGY | jq -c '.compiler')
          echo "INFO: Compilers are: $COMPILERS"

          # If 'mode' exists in JSON, print it; otherwise, handle gracefully
          MODES=$(echo $STRATEGY | jq -r '.mode')
          echo "INFO: Modes are: $MODES"

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    continue-on-error: true  # Allow build to fail
    needs: parse-matrix
    strategy:
      matrix:
        compiler: ${{ fromJson(needs.parse-matrix.outputs.compiler_matrix).compiler }}
        mode: ${{ fromJson(needs.parse-matrix.outputs.compiler_matrix).mode }}

      fail-fast: false #Ensures that jobs run in parallel
    name: build-${{ matrix.compiler.name }}-${{ matrix.mode.name }}
    steps:
    # TODO: Lots of repetition here on setting up the environments.
    - name: Check Disk Usage
      run: df -h
    - name: Getting CaNS
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Check Disk Usage
      shell: bash  # Specify the shell explicitly
      run: source ./tests/scripts/freespace.sh; source ./tests/scripts/reformat.sh
    - name: Getting CaNS
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Cache NVIDIA Compiler Suite
      uses: actions/cache@v3
      with:
        path: /opt/nvidia  # Change this if needed
        key: nvidia-suite-${{ runner.os }}-${{ hashFiles('**/dependencies.lock') }}
        restore-keys: |
          nvidia-suite-${{ runner.os }}-
    - name: Get packages
      shell: bash  # Specify the shell explicitly
      # TODO: avoid the if?
      run: |
           if [ ! -d "/opt/nvidia" ]; then
             source ./tests/scripts/install-NVIDIA.sh
           fi
    - name: Compile dependencies
      run: |
           source ./tests/scripts/setenv-${{ matrix.compiler.name }}.sh
           make libs FCOMP=${{ matrix.compiler.name }}
    - name: Upload compiled dependencies
      uses: actions/upload-artifact@v4
      with:
        name: compiled-libs-${{ matrix.compiler.name }}-${{ matrix.mode.name }}
        path: dependencies/
    - name: Compile CaNS
      run: |
           source ./tests/scripts/setenv-${{ matrix.compiler.name }}.sh
           make FCOMP=${{ matrix.compiler.name }} ${{ matrix.mode.flags }}
    - name: Upload CaNS
      uses: actions/upload-artifact@v4
      with:
        name: cans-${{ matrix.compiler.name }}-${{ matrix.mode.name }}
        path: run/cans
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: [build, parse-matrix]
    strategy:
      matrix:
        compiler: ${{ fromJson(needs.parse-matrix.outputs.compiler_matrix).compiler }}
        mode: ${{ fromJson(needs.parse-matrix.outputs.compiler_matrix).mode }}
        test-name: [start_stop]
      fail-fast: false #Ensures that jobs run in parallel
    name: test-${{ matrix.compiler.name }}-${{ matrix.mode.name }}-${{ matrix.test-name }}
    steps:
    - name: Maximize build space
      # From https://github.com/marketplace/actions/maximize-build-disk-space
      # The important stuff is to resize the partitions. Removals do not do much, if anything
      if: matrix.compiler.name == 'NVIDIA'
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 25000
        swap-size-mb: 30000
        remove-dotnet: 'true'
        remove-haskell: 'true'
        remove-docker-images: 'true'
        remove-android: 'true'
    - name: Getting CaNS
      uses: actions/checkout@v4
      with:
        submodules: false
    - name: Getting compiled libraries
      uses: actions/download-artifact@v4
      with:
        name: compiled-libs-${{ matrix.compiler.name }}-${{ matrix.mode.name }}
        path: dependencies/
    - name: Getting compiled CaNS
      uses: actions/download-artifact@v4
      with:
        name: cans-${{ matrix.compiler.name }}-${{ matrix.mode.name }}
        path: run/
    - name: Get packages
      shell: bash  # Specify the shell explicitly
      run: |
           sudo apt-get update
           echo "INFO: Installing the ${{ matrix.compiler.name }} compiler"
           if [ ${{ matrix.compiler.name }} == "NVIDIA" ]
           then
             args="YEAR=${{ matrix.compiler.year }} VERSION=${{ matrix.compiler.version }}"
           fi
           if [ ${{ matrix.compiler.name }} == "INTEL" ]
           then
             args="INTEL_VERSION=${{ matrix.compiler.intel_version}} HPC_VERSION=${{ matrix.compile.hpc_version }}"
           fi	   
           source ./tests/scripts/install-${{ matrix.compiler.name }}.sh $args
    - name: Get Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Get Python packages for testing
      shell: bash  # Specify the shell explicitly
      run: |
        python -m pip install --upgrade pip
        pip install numpy flake8 pytest f90nml
    - name: Run the test
      shell: bash  # Specify the shell explicitly
      run: |
           source ./tests/scripts/setenv-${{ matrix.compiler.name }}.sh
           chmod +x ./run/cans
           cd tests/${{ matrix.test-name }}
           if [ "${{ matrix.compiler.name }}" == "INTEL" ]
           then
           source ./testit-INTEL.sh
           else
           source ./testit.sh
           fi
    - name: Upload log files
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: logs-${{ matrix.compiler.name }}-${{ matrix.mode.name }}-${{ matrix.test-name }}
        path: run/*log
    - name: Print log(s)
      shell: bash  # Specify the shell explicitly
      run: |
           for f in $(ls run/*log)
           do
             echo "Printing the log file "$f
             cat $f
           done
